[workspace]
resolver = "3"
members = [".", "macros"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[package]
name = "serde_sc"
version.workspace = true
edition.workspace = true

[dependencies]
serde_sc_macros = { path = "macros" }
