[package]
name = "serde_sc_ts"
version.workspace = true
edition.workspace = true

[dependencies]
serde_sc = { path = "../serde_sc" }

[dev-dependencies]
serde = { version = "*", features = ["derive"]}
serde_json = "*"